
#include "DHT.h"
#include <Wire.h>
#include<Adafruit_BMP280.h>
#define DHTpin 13
#define DHTTYPE DHT11
#define ALTITUDE 18
#define SEA_LEVEL_PRESSURE 1013.25 
DHT dht(DHTpin, DHTTYPE);
Adafruit_BMP280 bmp;

//int pressure_sensor = 35;
int gas_sensor = 33;
int rain_sensor = 34;
int light_sensor = 32;


//variables for calliberation of sensor values......
float temp_slope = 1.0; // temperature
float temp_offset = -0.399;

float humidity_slope = 1.0; //humidity
float humidity_offset = 4.0;

float a = 1000.0; //light intensity
float b =-0.5; 
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/4ea90e61-5590-432f-bba0-eade272b5adf 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  CloudFrequency sound_Level;
  int air_Quality;
  CloudLuminance light_Intensity;
  CloudTemperature temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  Wire.begin();
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  
  /*   The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4*/
 
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
Serial.begin(115200); //Init serial port
  delay(10);


}
void loop() {
  ArduinoCloud.update();
   //air_Quality = analogRead(gas_sensor);
  //rain_Sensing = analogRead(rain_sensor);
   float rawPressure = bmp.readPressure() / 100.0;
   pressure = rawPressure / pow((1 - (ALTITUDE / 44330.0)), 5.255);
   altitude = bmp.readAltitude(SEA_LEVEL_PRESSURE);
  //sound_Level = analogRead(sound_sensor);
  light_Intensity = (analogRead(light_sensor));
  //float lux = a * pow(sensorValuelight, b);

  float temp = dht.readTemperature();
  temperature = (temp * temp_slope) + temp_offset;
  float humidity = dht.readHumidity();
  hUMIDITY=(humidity * humidity_slope) + humidity_offset;

}
  
/*
  Since AirQuality is READ_WRITE variable, onAirQualityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAirQualityChange()  {
  // Add your code here to act upon AirQuality change
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}


/*
  Since LightIntensity is READ_WRITE variable, onLightIntensityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightIntensityChange()  {
  // Add your code here to act upon LightIntensity change
}

/*
  Since SoundIntensity is READ_WRITE variable, onSoundIntensityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSoundIntensityChange()  {
  // Add your code here to act upon SoundIntensity change
}

/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}

/*
  Since Level is READ_WRITE variable, onLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLevelChange()  {
  // Add your code here to act upon Level change
}

/*
  Since SoundLevel is READ_WRITE variable, onSoundLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSoundLevelChange()  {
  // Add your code here to act upon SoundLevel change
}
